### ISSUE TITLE
Window in menu header

### ISSUE THREAD

**Issue by fosterc1** [nachocinalli/adapt-backgroundVideo#2]
Hello

We are using FW v5.28.0 / AT v0.11.1 

If a menu header background image is not added in the project settings the video does not show in the header, even though .menu__header has been added to the Selector field.

If a menu header background image is added in the project settings, the video shows under the added image.

This issue is replicated at page level as well, but is working at block level.

Thanks very much

![2023-03-10_15-00-02](https://user-images.githubusercontent.com/29701150/224350186-bbca51a4-b465-40b9-939d-2602d9df0d49.png)
![2023-03-10_15-02-27](https://user-images.githubusercontent.com/29701150/224350204-3e934ae2-5fff-40af-b921-22be2956f8ab.png)

**Comment by nachocinalli** [comment]
Hi Caleb!
Sorry, I can't replicate the issue. 
Is it possible that the video is behind the background color of the page header?
Try changing the value of z-index to 0:
.menu__header .backgroundvideo, .page__header .backgroundvideo {
    z-index: 0;
}

**Comment by fosterc1** [comment]
Ah, thanks very much

The plugin is working we just need to amend the theme.

Thanks very much

**Comment by nachocinalli** [comment]
No worries 👍
